# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-05 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='用户昵称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
    ]
